### ISSUE TITLE
send by sim2

### ISSUE THREAD

**Issue by mjheidari** [capcom6/android-sms-gateway#10]
how select sim for send?(sim1,sim2,..)

**Comment by capcom6** [comment]
Thank you for reporting the issue. Currently, app does not support selecting a specific SIM for sending SMS messages. It always uses the default SIM card.

I will consider adding the SIM-selection feature in future versions of app to provide more flexibility.

Please stay tuned for updates. Thank you for your understanding and support!

**Comment by capcom6** [comment]
Multiple SIM cards support added in https://github.com/capcom6/android-sms-gateway/releases/tag/v1.2.0
See `simNumber` field in request https://capcom6.github.io/android-sms-gateway/#/Messages/post-message
