### ISSUE TITLE
cloud server userName and password isnt showing

### ISSUE THREAD

**Issue by markus-azer** [capcom6/android-sms-gateway#104]
**Describe the Bug**
Thanks for great app and really so handful especially with encryption.
so the local server works great and even after opening router port it were accessible from outside

however im very struggling with cloud server, the user name and password doesnt show up even by
- reinstalling it multi times
- install older versions

**Expected vs Actual Behavior**
- Expected: cloud server userName and password 
- Actual: blank

**Screenshots**

**Environment**
- App Version: [1.16.2, 1.15.3]
- Mode: [Cloud]
- Operation: [sending/receiving SMS]
- Network Type: WiFi

**Smartphone**
- Device: Tecno la6
- OS: Android 7
- SIM Card Count: 1

**Checklist Before Submission**
- [x] I have described the bug in detail.
- [ ] I have provided the steps to reproduce.
- [ ] I have included screenshots (if applicable).
- [x] I have provided environment details.
- [ ] I have included relevant log file excerpts (if applicable).
- [x] I have read [FAQ](https://sms.capcom.me/faq/general/) and other relevant information.

**Comment by capcom6** [comment]
First of all, ensure that the server URL in the settings is empty; clear it if it is not. This way, the app uses the default URL `https://sms.capcom.me/api/mobile/v1`. After changing the URL, stop and start the app again from the Home tab.

Additionally, try to open https://sms.capcom.me/api/ from the device's browser to ensure that nothing is blocking it. The OpenAPI documentation should be shown at this URL. Another way to test access is to try using a mobile network to access the Internet.

If nothing helps, please provide the date and time with timezone of the last app start, so I can try to find logs for it.

**Comment by capcom6** [comment]
One more thing: do you have Google Play services or its open-source equivalent installed on your device?

**Comment by capcom6** [comment]
Hello!

Unfortunately, I didn't receive your answers, so I'll close the issue. However, please feel free to open a new one if you have any further questions.

**Comment by markus-azer** [comment]
Sorry my mistake forgot to update the issue.
The solution were pretty easy, just upgrade to the latest android version
