### ISSUE TITLE
DONT SEND SMS RESULT_ERROR_GENERIC_FAILURE

### ISSUE THREAD

**Issue by padgithub** [capcom6/android-sms-gateway#107]
**Describe the Bug**
`{
    "id": "2",
    "state": "Failed",
    "isHashed": false,
    "isEncrypted": false,
    "recipients": [
        {
            "phoneNumber": "...",
            "state": "Failed",
            "error": "Send result: RESULT_ERROR_GENERIC_FAILURE"
        }
    ],
    "states": {
        "Failed": "2024-08-19T04:50:08.049+03:00",
        "Pending": "2024-08-19T04:50:06.582+03:00",
        "Processed": "2024-08-19T04:50:06.724+03:00"
    }
}`

**To Reproduce**
1. Send request to API: endpoint
2. Go to tab message
3. See error

**Expected vs Actual Behavior**
- Expected: A clear and concise description of what you expected to happen.
- Actual: A clear and concise description of what actually happened.

**Screenshots**
![image](https://github.com/user-attachments/assets/52edde59-e463-49a7-b565-a65d117a0f7d)

**Environment**
- App Version: 1.18.0
- Mode: Cloud
- Operation: sending
- Network Type: WiFi

**Smartphone**
- Device: VISMART
- OS: Android 10
- SIM Card Count: 1

**Additional Context**
Add using samsung s20 android 13 same error

**Checklist Before Submission**
- [ ] I have described the bug in detail.
- [ ] I have provided the steps to reproduce.
- [ ] I have included screenshots (if applicable).
- [ ] I have provided environment details.
- [ ] I have included relevant log file excerpts (if applicable).
- [ ] I have read [FAQ](https://sms.capcom.me/faq/general/) and other relevant information.

**Comment by padgithub** [comment]
Srry. I found for bug:
my sim card is out of credit

**Comment by capcom6** [comment]
Thank you for your feedback. I will add this case to the FAQ.
