### ISSUE TITLE
Webhook Issue

### ISSUE THREAD

**Issue by Sat727** [capcom6/android-sms-gateway#109]
**Describe the Bug**
When making the API call to the application to setup webhooks, (in my case via localhost) the application never sends the webhook requests. NOR does it allow an ip such as: "http://192.168.0.242:8090" for local applications. I am recieving a 201 code, ensuring the data is json safe, checking the webhook via the URL request. I am not seeing any webhooks being sent out by the mobile application.

**To Reproduce**
1.  Setup the app as normal via localhost
2. Make the API call to setup a webhook (requests.post(url="http://192.168.0.123:8080/webhooks", auth=auth, headers={"Content-Type": "application/json"}, data=json.dumps({"id": "1", "url": "https://webhook.site/UUID I USED", "event": "sms:received"})))
3. Receive a 201 code and verify the webhook's existence at http://192.168.0.123:8080/webhooks
4. Send text to the device running the application
5. See no resulting webhook

(I've also tried this on other webhook capturing sites.)

**Expected vs Actual Behavior**
- Expected: Webhook to be received
- Actual: No data received

**Environment**
- App Version: 1.18.0
- Mode: Private
- Operation: Sending Webhook for incoming text
- Network Type: Wifi/Local

**Smartphone**
- Device: Galaxy A25
- OS: Android 14
- SIM Card Count: 1

**Additional Context**
Using LAN, no external servers.

**Comment by capcom6** [comment]
First of all, check the logs as described at https://sms.capcom.me/features/logging/.

In the UI, you can find basic information. For detailed information, please use the API.

Additionally, there may be issues with Android 14 due to recent changes in battery optimization. Please find any OS settings regarding battery optimization and disable it for the app.

**Comment by Sat727** [comment]
I forgot to add, no logs are being listed on the application. When I press the button for logs on the app, it shows empty, same as the API get request. I even tried an earlier version of the application and the issue still persists. Everything else seems functional. Texts are going through and the APK, as well as all other functions seem to be doing well. Very nice project, however, webhooks seem to not work at least for this version. Additionally, all battery optimization options are off.

**Comment by Sat727** [comment]
Actually seems only the recieving event isn't working. It is only sending sent events

**Comment by capcom6** [comment]
It seems like the Android OS does not notify the app when a message is received for some reason. Please verify that you have granted the "Receive SMS" permission to the app.

Unfortunately, I don't have a physical Android 14 device near me to test it right now. I will try to test it next week.

**Comment by capcom6** [comment]
Oh, you've already found the solution. Thanks for your feedback!
