### ISSUE TITLE
webhook sms:received never sends

### ISSUE THREAD

**Issue by jaeblaze1989** [capcom6/android-sms-gateway#129]
**Describe the Bug**
when sending an sms to the device with the app installed. all the API functions are working. apart from checking recived messages. when a message is sent to the device. the webhook is never sent.

**To Reproduce**
1. make sure the server is running and a webhook endpoint is added.
2. send a message to the server.
3. no webhook data is sent to the configured endpoint

**Environment**
- App Version: latest
- Mode: local
- Operation: receiving SMS
- Network Type: WiFi/Mobile Data

**Smartphone**
- Device: galaxy note 10+
- OS: android 12
- SIM Card Count: 1

**More Informtation**
had the device hooked up to android studio to access logcat. i never see any type of event trigger to initiate the webhook

**Comment by capcom6** [comment]
Hello!

Please consider checking the following:

1. Do any other webhooks work in the app?
2. Are you using the default messaging app on the device? Third-party apps can sometimes block SMS-related events.
3. Verify that you have provided permissions for receiving SMS messages to the app.
4. Are there any logs regarding this messaging issue in the app's Settings tab, under the Logs section? In Local mode, you can also access the logs through the API: https://sms-gate.app/features/logging/#accessing-logs

If none of these steps resolve the issue, please provide more details about your setup and any error messages you encounter.

**Comment by jaeblaze1989** [comment]
thanks for the reply,

1. other webhooks are working.
2. yes the default messaging app is used. 
3. app has all permissions required.
4. logs work but only for other webhooks not sms:received

device is a samsung galaxy note 10+
messenger app is the only one on the device as default.  (device was factory reset before app install)
permissions are as follows:
read phone status and identity
send and view sms messages
receive text messages


it would appear that incomming sms never trigger the webhook.
is there a SMS app that is know to work. i belive the default one on this device is samsung messenger.

**Comment by capcom6** [comment]
To clarify, have you sent messages to yourself from the same phone? And what do you mean by "don't register with the device"?

**Comment by jaeblaze1989** [comment]
no the messages are from a different samsung device.   after more testing. i had people send sms to it from iphones. and it works.
and some people from android and it did not work.

this lead me to belive there is somthing else going on.

and i belive i have found the problem.   RCS messages dont trigger the webhook.
after going into the message app and forcably disableing RCS messages on the device with the app.  it now appears to be working.

it may be worth adding to the documentation on how to disable RCS messages

i installed googles SMS messenger. and disabled samsungs.  then i went into message settings > RCS chats    and turned it off.  Samsung messenger does not have this option from what i can see.

this only has to be done on the recieving device. not the sender.
