### ISSUE TITLE
Delay Functionality Doesn't Work

### ISSUE THREAD

**Issue by unrealmaow** [capcom6/android-sms-gateway#130]
**Describe the Bug**
When setting up the minimum and maximum delay and maximum number of message deliveries per 1 min from settings. It doesn't work at all.

**To Reproduce**
Steps to reproduce the behaviour:
1. Set the values of delays and maximum number of deliveries per 1 min from settings.
2. Send Bulk Messages with multiple recipients in the PhoneNumbers object. The delay doesn't work at all.

**Expected vs Actual Behavior**
- Expected: Proper Delay between sending messages as configured in settings.
- Actual: There is no delay between sending messages.

**Checklist Before Submission**
- [x] I have described the bug in detail.
- [x] I have provided the steps to reproduce.
- [ ] I have included screenshots (if applicable).
- [ ] I have provided environment details.
- [ ] I have included relevant log file excerpts (if applicable).
- [x] I have read [FAQ](https://sms-gate.app/faq/general/) and other relevant information.

**Comment by capcom6** [comment]
Hello!

I'd like to clarify a few points about the delay functionality:

1. The delay feature works between individual messages, not between recipients in a single message.
2. The app is not designed for bulk message sending, as I don't want my app to be used for spam.

To use the delay feature effectively, please try the following:

1. Send multiple messages with one or a few recipients in each message.
2. The delay will be applied between these separate messages.

I'll update the documentation to make this behavior clearer.
