### ISSUE TITLE
MISSING_INSTANCEID_SERVICE

### ISSUE THREAD

**Issue by zhex900** [capcom6/android-sms-gateway#131]
I have installed the latest sms-gateway app [v1.19.2](https://github.com/capcom6/android-sms-gateway/releases/tag/v1.19.2)

After turning on the cloud server, and click the OFFLINE button to ONLINE. This is a fresh install. All the configurations is default.

I get this java exception MISSING_INSTANCEID_SERVICE

Is this something to do with the firebase configuration? 

Anything I should do?

**Comment by capcom6** [comment]
It seems like the app can't obtain the FCM (Firebase Cloud Messaging) token.
To resolve this:

1. Ensure that Google Play Services is installed and up-to-date on your device. The app uses FCM in Cloud mode to notify the device about new messages to send from the server.

2. If Google Play Services is installed and up-to-date, try clearing the cache and data for both Google Play Services and the SMS Gateway app, then restart your device.
