### ISSUE TITLE
[feature] Add a custom password to the local/remote server

### ISSUE THREAD

**Issue by alexjircan** [capcom6/android-sms-gateway#138]
**Is your feature request related to a problem? Please describe.**
It would be nice if you could set a custom password for the local/cloud server to enhance security. 
In the future, it would also be beneficial to have the possibility of adding an identity provider and securing endpoints with S2S tokens.

**Comment by capcom6** [comment]
Hello!

Thank you for your feature request!

Currently you can reinstall the app on your device to obtain entirely new credentials. This approach provides increased privacy as it changes both the username and password.

While custom passwords can potentially be more secure than generated ones, users often choose less secure passwords for ease of remembrance. However, I understand the desire for more control over security settings and will add this feature to my backlog.

Regarding server-to-server communication, I have plans to introduce a new version of authentication using JWT, at least for Cloud/Private servers. In the long term, I'm also considering implementing OAuth.
