### ISSUE TITLE
Add Setting to Ignore HTTPS for Local Network Connections in Webhooks

### ISSUE THREAD

**Issue by UnelDev** [capcom6/android-sms-gateway#139]
Hello, I am experiencing an issue with the /webhook function. I would like to connect to a local server, but it seems impossible to do so because HTTP connections are not allowed. I tried setting up an HTTPS server with a self-signed certificate, but that didn't work either.

Would it be possible to add an option to toggle this protection, or to disable it for local network connections?

**Comment by UnelDev** [comment]
Hello, I created a certificate as instructed in the link, but it still doesn't work. In the application logs, there’s this error: "Webhook failed with retry: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found."

The certificate is properly installed.

Thank you.
![Screenshot_20241107-180811](https://github.com/user-attachments/assets/6be5a393-09f6-47e9-ae94-8a329f67e8d5)

**Comment by darksources** [comment]
I can confirm using the methods described in the website (using the same server.conf with CN the ip of https server). I can confirm that the webhooks are indeed firing against the server with TCPdump. 

Server is apache

**Comment by capcom6** [comment]
First, ensure that you have the correct certificates/keys in the appropriate locations. You can use `curl` to debug the connection.

Since the SSL connection itself is not part of the app, I can't provide assistance without fully understanding your server and phone configuration, particularly regarding network and SSL settings.

For a complete diagnosis, I need the following information:

1. Webhook URL
2. Contents of the `server.cnf` file used for certificate generation
3. Names of generated certificates and keys
4. Web server name/example code and configuration related to SSL
5. Screenshot of the installed root certificate on the device
6. Result of the `curl` command: `curl -vv --cacert ca.crt https://your-webhook-url.com`

If you prefer not to share this information here, you can contact me directly at support@sms-gate.app.

**Comment by UnelDev** [comment]
thank you for this quick response
Webhook URL: `"https://192.168.1.94/sms"`

`server.cnf`:
```cnf
[req]
distinguished_name = req_distinguished_name
x509_extensions = v3_req
prompt = no

[req_distinguished_name]
C = US
ST = California
L = Los Angeles
O = Internet Corporation for Assigned Names and Numbers
OU = IT Operations
CN = 192.168.1.94

[v3_req]
keyUsage = nonRepudiation, digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth
subjectAltName = IP:192.168.1.94
```

Generated certificate and key names: `ca.crt`, `ca.key`, `server.cnf`, `server.crt`, `server.scr`, `server.key`

Server code:
```ts
import chalk from 'chalk';
import { config } from 'dotenv';
import express from 'express';
import fs from 'fs';
import https from 'https';
import { AddressInfo } from 'net';
import Switchboard from './Switchboard';
import { IsPhoneNumber } from './tools/tools';

config();
const app = express();
app.use(express.json());

const switchboard = new Switchboard();

const options = {
	key: fs.readFileSync('server.key'),
	cert: fs.readFileSync('server.crt')
};

const server = https.createServer(options, app);

server.listen(443, () => {
	console.log('Listening on port ' + (server.address() as AddressInfo).port);
});

app.post('/sms', (req, res) => {
	const smsData = req.body;

	console.log('SMS received:', smsData);

	const message = smsData.message;
	const sender = smsData.from;

	console.log(`Message from ${sender}: ${message}`);

	res.sendStatus(200);
});
```
![signal-2024-11-08-214801_003](https://github.com/user-attachments/assets/788d9b2d-88ab-4159-9e19-968379ddddba)
![signal-2024-11-08-214801_002](https://github.com/user-attachments/assets/e9708919-d787-47e3-906e-d9ef86a43ff0)

**Comment by capcom6** [comment]
The output of curl confirms that the server is configured correctly. However, there's a suggestion for your `server.cnf` file: please use the `alt_names` section as shown in the FAQ to mitigate any inconsistencies:

```
...
subjectAltName = @alt_names
[alt_names]
IP.0 = 192.168.1.94
```

I've tested the guide from the FAQ once more with NodeJS, and everything works fine. As another step, please try the attached files:

- `ca.crt` - install this on the device
- `server.crt` and `server.key` - use these on the server

[certs.zip](https://github.com/user-attachments/files/17685202/certs.zip)

**Comment by UnelDev** [comment]
ok thank you very much, with this certificate, everything works correctly.
thanks you
