### ISSUE TITLE
Request: Automatic SIM Rotation Based on SMS Recipient Limits

### ISSUE THREAD

**Issue by forkyboy** [capcom6/android-sms-gateway#148]
First and foremost, thank you for developing the SMS Gateway for Android™—it's an invaluable tool for many of us.

I wanted to bring to your attention a challenge that users in Europe often face. Many mobile operators advertise "unlimited SMS" plans; however, they frequently impose hidden restrictions, such as limiting the number of unique recipients per month—typically ranging from 99 to 250. This poses significant challenges for transactional e-commerce businesses, as even small shops can quickly reach these recipient limits, leading to service disruptions and potential customer dissatisfaction.

Proposed Solution:

To address this issue, I propose implementing an automatic SIM rotation feature within the SMS Gateway application. Modern Android devices often support multiple SIM cards, including eSIMs, making it feasible to manage several SIMs simultaneously. By incorporating a feature that automatically switches the active SIM card once a predefined recipient limit is reached, businesses can distribute messages across multiple SIMs, adhering to individual SIM limits and ensuring continuous operation.

Implementation Suggestions:

Multiple SIM Management: Enhance the application to recognize and utilize multiple SIM cards installed on the device.

Automatic SIM Rotation: Develop functionality that:

Tracks the number of recipients each SIM has messaged within the billing cycle.
Automatically switches to an alternate SIM when the current one approaches its limit.
User-Defined Limits: Allow users to specify the monthly recipient limit for each SIM, ensuring compliance with operator policies.

By integrating these features, the SMS Gateway can operate seamlessly within the constraints of European mobile operators, maintaining reliable service for transactional e-commerce activities.

Thank you for considering this feature request. I believe it would significantly enhance the application's utility for users facing these limitations.

**Comment by capcom6** [comment]
Hello!

Thank you for your request!

I understand your problem, but I don't see a universal solution. There may be many combinations of restrictions, not just "unique recipients". It might be more useful to implement message routing on the sending side. The app already supports working with multiple SIM cards by utilizing the `simNumber` field in the request.

And there is a question: what should be done if limits on all available SIM cards are reached?

As an alternative solution, I can implement a round-robin mode for selecting SIM cards on the device. If a request doesn't contain an explicit SIM card number, it will be selected by round-robin mode for each message: 1, 2, 1, 2, and so on.

Also, there is already another feature in my backlog: allowing the registration of multiple devices on a single account and automatically switching between them. While this feature is not directly related to your request, it can increase the number of SIM cards on a single account.

I've added your idea of implementing a per-SIM message limit to backlog. However, I can't confirm that it will be implemented in the near future. I need some time to think about the best way to approach this.

Thank you for your understanding and for helping improve the app.

**Comment by forkyboy** [comment]
Thank you for your thoughtful reply and for considering my feature request. I understand that implementing a universal solution is complex, and I appreciate your efforts to evaluate the best approach.

In my use case, the app is being used to send transactional SMS for small to medium-sized e-commerce stores. Typically, one device with one physical SIM and two eSIMs is more than sufficient. Let me explain further:

For example, if there’s a 200-recipient limit per SIM, this setup would allow for around 600 unique customers to be reached monthly. This volume is ideal for small to medium-sized businesses. Larger e-commerce stores often turn to services like Brevo (formerly Sendinblue) or similar platforms, as they have the capital to invest in those solutions. However, my customers are usually "mom-and-pop" shops that can’t afford to pay upwards of 10 cents per SMS. That’s why they’re drawn to more cost-effective alternatives like this app.

I hope this sheds some light on how the feature might be used and the specific audience it would serve. Thank you again for your consideration and for working to improve the app for users like us!

**Comment by capcom6** [comment]
Thank you for the detailed information.

The question for now is: would a simple SIM card rotation like round-robin without any limit be sufficient?

The difference from your proposed solution is that the SIMs would be rotated constantly (1-2-3-1-2-3...), not after reaching any limit. So if you sent 200 messages, they would be equally distributed among the 3 SIMs, rather than using just the first SIM as you proposed in the initial message.

**Comment by forkyboy** [comment]
i think that will work fine yes, it is a good solution.
