### ISSUE TITLE
support dial and pick up phone call

### ISSUE THREAD

**Issue by ghost** [capcom6/android-sms-gateway#159]
**Is your feature request related to a problem? Please describe.**
support call gateway as well

**Describe the solution you'd like**
support dial and pick up phone call

**Describe alternatives you've considered**
https://github.com/chenxiaolong/BCR
https://github.com/chenxiaolong/BCP

**Additional context**

**Comment by capcom6** [comment]
Thank you for your feature request!

I have no plans to implement any call features in this app. As the name suggests, it is an SMS Gateway. I prefer to follow the Unix philosophy: do one thing and do it well.

There are additional reasons for this decision:

1. Android imposes significantly more restrictions on call handling compared to SMS. 
2. The alternatives you've mentioned (BCR and BCP) require root privileges to function properly. In contrast, the SMS Gateway can operate without any modifications to the phone's operating system.

However, I am considering developing a separate app for call-related features, as your request is not the first of its kind. At this time, I cannot provide a specific timeline for such a project.

Thank you for your understanding and continued interest in improving the app!
