### ISSUE TITLE
Adding an API GET to read received SMS

### ISSUE THREAD

**Issue by olaxe** [capcom6/android-sms-gateway#16]
Hello,

Thanks for your nice project. Do you think you can add an option to read received SMS? It is useful when someone answers to the automated SMS or to ask a question and retrieve automatically the answer.

**Comment by capcom6** [comment]
Hello,

Right now, this app is all about sending SMS. Receiving wasn't in the original plan, but I'll give it some thought.

Thank you for your suggestion.

**Comment by olaxe** [comment]
many thanks for your consideration.

**Comment by olaxe** [comment]
I found this app in the meantime: https://github.com/bogkonstantin/android_income_sms_gateway_webhook
It's fulfill my needs. I run both to have the way in and out.

**Comment by rayenking** [comment]
Yea waiting for this feature :"

**Comment by capcom6** [comment]
Good news, everyone!

I'm delighted to announce that the application now includes the capability to send webhooks when new SMS messages are received. This new feature is available for you to test via the pull request at https://github.com/capcom6/android-sms-gateway/pull/76. The webhook functionality has been integrated into all operational modes: Local, Cloud, and Private.

Now, you might be wondering why I didn't just add a `GET` endpoint. There are a couple of solid reasons for this decision:
1. Security is a top priority, and a `GET` endpoint could be accessed at any time, potentially exposing sensitive information. On the other hand, webhooks are pushed securely to your own server. Moreover, in Cloud mode, a `GET` endpoint would necessitate transferring all messages from your device to the Cloud server, raising significant privacy concerns.
2. Efficiency is key in event-driven systems, such as SMS reception. Constantly polling a `GET` endpoint for new messages is resource-intensive, leading to unnecessary server load and increased battery consumption on the device. Webhooks, however, are event-driven and are triggered only when there is an actual new message, optimizing both server and device resources.

An example configuration for the webhook setup can be found at https://sms.capcom.me/getting-started/webhooks/. Rest assured, I'm working on crafting more comprehensive documentation to guide you through the process.

Thank you for your continued support, and I'm confident you'll find this new webhook feature to be a significant enhancement to your experience.
