### ISSUE TITLE
Update libphonenumber dependency

### ISSUE THREAD

**Issue by hsul4n** [capcom6/android-sms-gateway#26]
Hello there..

I'am having an issue while sending to some new phone numbers and I figured out that new format number was published earlier in *libphonenumber* [8.13.3](https://github.com/google/libphonenumber/blob/4834a3bf394bb945b0cb8366cf290666bb91a66f/resources/carrier/en/967.txt) and the current used version is [8.12.32](https://github.com/capcom6/android-sms-gateway/blob/44323892a6b904fbf5ff7e115454960f55e8a2f4/app/build.gradle#L104)..

Upgrading *libphonenumber* to latest version [8.13.27](https://github.com/google/libphonenumber/releases/tag/v8.13.26) will fix that issue.

**Comment by capcom6** [comment]
Hey there,

Thanks for letting me know about this issue.

If you're using the local server mode, you can give version 1.3.1 a try from our GitHub releases [here](https://github.com/capcom6/android-sms-gateway/releases/tag/v1.3.1). If you're using the cloud server, I'll update the server in the next few days to include the latest libphonenumber version.
