### ISSUE TITLE
Add delays between sends

### ISSUE THREAD

**Issue by MarchenkoOleg** [capcom6/android-sms-gateway#33]
Thanks for your application, we started using it. Some mobile operators don't like it when messages are sent in batches at once. It would be nice to add functionality when it would be possible to set the delay in seconds/ minutes between sends, and even better, the delay range so that they are random :)

**Comment by issasaleh** [comment]
Yes that would be useful to set a random delay between every messages

**Comment by capcom6** [comment]
Hi there!

Give version 1.6.0 a go: https://github.com/capcom6/android-sms-gateway/releases/tag/v1.6.0

I've introduced a delay feature where you can set a maximum delay time. The app will then randomly select a delay between 0 and your specified maximum for each message sent.

Please let me know how it works for you!
