### ISSUE TITLE
Add message limits 

### ISSUE THREAD

**Issue by MarchenkoOleg** [capcom6/android-sms-gateway#34]
Almost all mobile operators limit the number of SMS messages per day, for example, 100 pcs/day. I would like to add functionality that would take this into account and postpone the message queue until the reset time. That is, two parameters are needed: the limit per day, and the time to reset the limit.

**Comment by MarchenkoOleg** [comment]
You can complicate it to set a limit period, let's say the amount per hour, the amount per month

**Comment by issasaleh** [comment]
Yes that would be useful to set a random delay between every messages.
