### ISSUE TITLE
same phone as sms and wifi gateway/router works!

### ISSUE THREAD

**Issue by hmollercl** [capcom6/android-sms-gateway#52]
Amazing program.
I'm just here to tell that if you want to use the same phone as sms gateway and wifi gateway/router, it works, although this program does not tell you the local ip.
My use case is that I need to send sms message even when electricity fail so I need wifi network to be active (and sms gateway to) this is easier if one device do it all and for that using the same phone is ideal. 

Activate tethering on the phone and connect to the wifi network the phone create. The only "issue" is that android-sms-gateway don't tell you the local IP so you need to discover it. 
In esp I use 
`WiFi.gatewayIP().toString(); `
from 
`#include <WiFi.h>`
after I connect to the phone wifi network.

**Comment by capcom6** [comment]
Hello!

Thank you for sharing your experience with the project! With regard to discovering the local IP in tethering mode, I'll certainly look into it.
