### ISSUE TITLE
 Endpoint by SSL, date and time of SMS delivery

### ISSUE THREAD

**Issue by djm03** [capcom6/android-sms-gateway#59]
Thank you for the great project.

Two questions about this:

1. When using the local server, is there a way to secure the access to the endpoint by SSL?

2. Can the date and time of SMS delivery be transmitted in the response, in addition to [state] => Delivered?

**Comment by capcom6** [comment]
Hello!

1. Currently, the local server doesn't natively support SSL/TLS. This mode is intended for use within private and trusted networks, and I advise against exposing the local server to public access without any security measures. However, you can set up a reverse proxy such as Nginx to handle SSL/TLS termination.

2. Regarding the transmission of the date and time of SMS delivery, this feature is not available at the moment. I will look into the possibility of implementing this functionality.

**Comment by djm03** [comment]
Hello!

Thanks for the information. Where have the reverse proxy to be running, on the Android device? Do you have instructions for setting this up?

**Comment by capcom6** [comment]
It's not common to run a reverse proxy directly on an Android device. Typically, a reverse proxy would run on a separate piece of hardware within your local network. This could be on a router that supports custom firmware and has the capability to run a reverse proxy, or it could be on a dedicated server or another computer in your network.

The general communication flow would look something like this:

`Internet -> [Router] -> [Reverse Proxy] -> [Android Device]`

In this setup, the parts within the parentheses represent your local network. The reverse proxy serves as a gateway that manages incoming Internet requests and directs them to your Android device.

If you're looking for a more straightforward solution, you might want to explore the Public Cloud Server mode. It's designed to be easier to set up and might be better suited for your needs if you're looking to avoid the complexity of configuring a reverse proxy. You can find more information and a guide to get started here: https://sms.capcom.me/getting-started/public-cloud-server/.

See also https://github.com/capcom6/android-sms-gateway/issues/20
