### ISSUE TITLE
Add Version Info in the App

### ISSUE THREAD

**Issue by darigh** [capcom6/android-sms-gateway#64]
Hello Very Great App!!
It will be nice to see "App version release" inside the App.

**Comment by capcom6** [comment]
Hello!

Thank you for your suggestion! I've added it to my backlog.

In the meantime, you can view the current version of the app in your phone's settings, typically under the Applications section.

**Comment by capcom6** [comment]
Hello!

I have added the app version information to the Settings page in [v1.12.4](https://github.com/capcom6/android-sms-gateway/releases/tag/v1.12.4)
