### ISSUE TITLE
crashed with local server on android 6

### ISSUE THREAD

**Issue by hmollercl** [capcom6/android-sms-gateway#65]
Hi, I was trying to make it run in a Samsung J2 Prime with Android 6 with local server, but when I enable local server and press to start it (hit offline to make it online) it crashes. 
First run it crashes soon after I give the privileges to send sms, following times it is each time I start (hit offline) in local server. 
With cloud server it does not happens.

I have tested in 3 different phones with versions 1.12.1 and 1.12.2

Is there possible start with debug mode to see what happens?

**Comment by capcom6** [comment]
Hello,

Thank you for bringing this to my attention. I have tested the app on Android 6 and discovered an issue related to date formatting when Local Server mode is enabled. I've addressed this problem in a new pull request. Could you please try the APK from the PR [here](https://github.com/capcom6/android-sms-gateway/blob/artifacts/pr66-app-release.apk?raw=true) and let me know if it resolves the issue on your device?

**Comment by hmollercl** [comment]
PR 66 worked ok! Thanks!

**Comment by capcom6** [comment]
Thanks for your feedback!
