### ISSUE TITLE
Username and password 

### ISSUE THREAD

**Issue by kakapagal** [capcom6/android-sms-gateway#69]
I am. unable to find username and password for api,

In app settings there is no option I found for setup username and password.

**Comment by capcom6** [comment]
Hello!

The username and password are generated automatically upon the first launch of the app, either in local or cloud mode. Currently, the app does not support the use of custom credentials. However, you can reinstall the app to generate new ones.

To proceed, simply choose one of the modes on the "Home" screen and then press the `OFFLINE` button located at the bottom.
