### ISSUE TITLE
error android.permission.MANAGE_SUBSCRIPTION_USER_ASSOCIATION

### ISSUE THREAD

**Issue by hasanbasri1993** [capcom6/android-sms-gateway#73]
"error": "Sending: getSubscriptionUserHandle. Does not have any of the following permissions. [android.permission.MANAGE_SUBSCRIPTION_USER_ASSOCIATION]",
            "phoneNumber": "+xxxxxxxxxx",
            "state": "Failed"

**Comment by capcom6** [comment]
Hello,

Thank you for reaching out. To assist you better, could you please provide the following details?

- The model of your device and the Android version it's running.
- The version of the app that you're experiencing this issue with.

Also, please confirm if you granted all the requested permissions when you first launched the app. It would be helpful if you could share a screenshot of the permissions for the SmsGateway app found in the Android Settings under Apps.

The permission mentioned in the error is not part of the official Android documentation. Additionally, the app does not explicitly call the `getSubscriptionUserHandle` method, which suggests that this could be related to vendor specific issue.

Looking forward to your reply to resolve this issue promptly.

**Comment by hasanbasri1993** [comment]
Redmi Note 8
i use custom rom 
https://pixelos.net/download/ginkgo

![IMG_5669](https://github.com/capcom6/android-sms-gateway/assets/6375150/f73b490f-75e3-478c-8510-8554116236d2)

![IMG_5670](https://github.com/capcom6/android-sms-gateway/assets/6375150/90474e30-f9e8-4478-8a8a-9b6f3a32f8d8)

![IMG_5671](https://github.com/capcom6/android-sms-gateway/assets/6375150/0466123c-b8d1-4631-aa5e-6adc4e742171)
Here Phone call and SMS was granted

**Comment by hasanbasri1993** [comment]
i try to add


--
  | <uses-permission android:name="android.permission.MANAGE_SUBSCRIPTION_USER_ASSOCIATION"/>

into AndroidManifest.xml
it's work now

**Comment by capcom6** [comment]
Thank you for your feedback!

I have added this permission to the manifest in https://github.com/capcom6/android-sms-gateway/pull/74. I will conduct tests on my devices running stock firmware to ensure everything functions correctly before including it in the upcoming release.
