### ISSUE TITLE
Sender ID and/or 1-Way SMS?

### ISSUE THREAD

**Issue by developeryps** [capcom6/android-sms-gateway#75]
Hi, thanks for this app, it works great!

Is there any way to add a Sender ID and/or 1-Way SMS?

E.g. received SMS come from 'MyCompany' (Sender ID) rather than the phones full mobile number (in countries that support this, e.g. UK) and 1-Way SMS meaning the recipient can't reply to the SMS?

https://gatsby-staging.clickatell.com/help-center/sms/country-regulations/what-is-sender-id/

https://www.smsglobal.com/blog/two-way-sms-vs-one-way-sms-which-is-better/#:~:text=With%20a%20one%2Dway%20SMS,extent%20of%20one%2Dway%20SMS.

Thanks again.

**Comment by capcom6** [comment]
Hello,

Thank you for your feedback and for using the app!

Currently, the app sends messages using the device's SIM card, similar to any default messaging app on your phone. Therefore, if your default messaging app supports sending messages with a Sender ID or 1-Way SMS, this app should also support these features. However, I am not aware of any mobile operators that provide these features directly through a customer's SIM card. I would recommend reaching out to your mobile operator for more information on this.
