### ISSUE TITLE
result RESULT_ERROR_LIMIT_EXCEEDED

### ISSUE THREAD

**Issue by hasanbasri1993** [capcom6/android-sms-gateway#81]
hi 
here i try to send 1000 numbers
Redmi Note 8
i use custom rom
https://pixelos.net/download/ginkgo

How to set always allow ?
![2024-06-21_19-01](https://github.com/capcom6/android-sms-gateway/assets/6375150/b2f92760-192d-4174-80eb-9d1629b03e5c)

And in delivery status many number  got error Send result: RESULT_ERROR_LIMIT_EXCEEDED state": "Failed"

Thank u

**Comment by hasanbasri1993** [comment]
solved by this

[https://www.xda-developers.com/change-sms-limit-android/](url)

**Comment by capcom6** [comment]
Thank you for sharing the solution. I will include this in the FAQ section to assist others who might encounter the same issue.
