### ISSUE TITLE
Not Receiving Message While in Background

### ISSUE THREAD

**Issue by rayenking** [capcom6/android-sms-gateway#90]

**Comment by rayenking** [comment]
I have to open the app again to receive the message

**Comment by capcom6** [comment]
Hello, @rayenking 

Could you please provide a bit more detail on the following?

1. Are you referring to sending SMS via API or receiving them through a webhook?
2. What version of the app are you currently using?
3. Which Android version is installed on your device?
4. Are you using the stock messaging app on your device, or do you have an alternative messaging app installed?
5. In which mode are you using the app (e.g., Local, Cloud, or Private Server)?
6. Could you provide the steps to reproduce the problem, including any relevant API requests (without including credentials)?

This information will greatly assist us in diagnosing and addressing the issue more effectively.

**Comment by rayenking** [comment]
> Hello, @rayenking
> 
> Could you please provide a bit more detail on the following?
> 
> 1. Are you referring to sending SMS via API or receiving them through a webhook?
> 2. What version of the app are you currently using?
> 3. Which Android version is installed on your device?
> 4. Are you using the stock messaging app on your device, or do you have an alternative messaging app installed?
> 5. In which mode are you using the app (e.g., Local, Cloud, or Private Server)?
> 6. Could you provide the steps to reproduce the problem, including any relevant API requests (without including credentials)?
> 
> This information will greatly assist us in diagnosing and addressing the issue more effectively.

Sure..

1. I tried both sending SMS via API and receiving SMS via webhook.
2. I am using the latest version (1.16.0).
3. 14
4. No, just the default system app.
5. Local
6. First, I opened the app and tried to send and receive SMS (I had to set up the server and send the webhook), and it worked. Then I went to the home (the app still in recent), waited for 3-5 minutes, and tested again. The sending API could not respond and was still sending (using Postman). When I opened the app again, the API successfully sent the SMS. The same issue occurred with receiving SMS.

**Comment by capcom6** [comment]
I need some time to test the issue on Android 14.

However, please check the following points regarding sending messages:
1. After you open the app and select Local mode, if you press the Offline button to change it to Online, does a notification appear in the status bar?
2. After you put the app in the background and try to send a message through the API, what error do you receive on the sending side?
3. If you're unable to send the message and before you reopen the app, does the notification icon remain in the status bar?
4. Does your device have any power-saving settings enabled? Have you tried disabling any battery optimizations, including turning off WiFi when not in use?

Regarding webhooks:
1. If you send a message while the app is in the background, is the webhook for this message sent after you reopen the app? Or are only the messages received while the app is in the foreground processed, and others skipped?

Thanks.

**Comment by rayenking** [comment]
For sending messages:

 1. Yes, the notification appears in the status bar.
 2. No errors, but it seems like Postman keeps trying to send until it times out.
 3. Yes, the notification remains in the status bar.
 4. I had to disable power saving and select the unrestricted battery optimizations.
For webhooks:

 1. Yes, the message is sent to my server after reopening the app.
 
Overall, this is a nice app.

**Comment by capcom6** [comment]
Okay, based on the provided information:
- Since there is an icon in the status bar, the local server of the app is running. Therefore, Postman's timeout suggests there might be a network issue.
- Since you eventually receive the webhook, the app successfully processes the incoming SMS in the background and adds it to the queue for sending the webhook. The only reason for adding to the queue without immediately sending would be the absence of a network connection.

Are you sure that you have to open the app to get it working? Or is it enough to turn on the device screen or unlock it? Does your device respond to a ping when you can't connect to the app?

Finally, there's both good and bad news:

- Good news: I think I've found the cause of the problem. The app didn't lock WiFi in the on state.
- Bad news: In Android 14 and higher, there's no way for the app to lock WiFi in the on state when the screen is off. Therefore, it is recommended to try Cloud or Private Server mode on your device.

Anyway, I'll update the app to lock WiFi in the on state in a few days and provide you with a test version.

Sources:
- https://developer.android.com/reference/android/net/wifi/WifiManager#WIFI_MODE_FULL_HIGH_PERF
- https://developer.android.com/reference/android/net/wifi/WifiManager#WIFI_MODE_FULL_LOW_LATENCY

Thank you for your patience.

**Comment by rayenking** [comment]
Yeaa I am sure, I have to reopen the app to get working.
Well, yeah, I forgot there was a cloud. Let me try it.

**Comment by rayenking** [comment]
https://github.com/capcom6/android-sms-gateway/assets/122691366/0ed75b6a-d181-43b2-aad4-ac409d99070e

Maybe with this, you can see more clearly.

**Comment by capcom6** [comment]
Thanks for providing the video.

The only reason I can see for this behavior involves Android 14's actions to save battery power, such as disabling network access for the app after some time in the background. From the app's perspective, everything appears to be functioning correctly.

I noticed you've activated pings in the app. Did the ping webhooks not work as well? And what about pinging your device from a PC? Do you have another device with an Android version prior to 14 to test with?

Please test the app in Cloud mode; it uses PUSH notifications for sending. Webhooks should work the same, so I need some extra time for testing. I'm currently testing the app with Android 14 using an emulator, as I don't have a real device with Android 14 at the moment.

**Comment by rayenking** [comment]
Okey, I'll try it on another phone with Android 14's and try using cloud maybe can be helpful.
Well I've tested it on Android 13's and there's nothing problem like this just normal ^_^

**Comment by rayenking** [comment]
Sorry I have problem with cloud, the server response says Unauthorized, I have to set the basic authorization

**Comment by rayenking** [comment]
Update: It looks like the trouble is with the phone. I've tested on Android 14 with a POCO X5 5G, and it worked normally.

**Comment by capcom6** [comment]
Regarding requests to the cloud, the `/mobile` endpoints are intended for use by devices, not by end-users. For integration with the app, please use the `/3rdparty` endpoints. See https://capcom6.github.io/android-sms-gateway/ for more details.

Thank you for your feedback. It's possible your initial device has some modifications to the OS or additional settings for battery power optimization that affect network connection usage.

Do you have any other questions, or may I close this issue?

**Comment by rayenking** [comment]
Nothing. Thank you for the help, I'll close the issue,,,

**Comment by rayenking** [comment]
Just a heads up: if someone has the same issue as me, using the cloud can be helpful
