### ISSUE TITLE
multiple SMS simultaneously,

### ISSUE THREAD

**Issue by watata84** [capcom6/android-sms-gateway#91]
Describe the Bug
When sending multiple SMS simultaneously, a popup appears asking for permission to send messages, despite having changed the settings to allow premium SMS and not ask for permission.

To Reproduce

Send request to API: `POST /send-sms` with payload:
```json
{
  "phone_number": "+1234567890",
  "message": "Test message"
}
```

Send multiple SMS simultaneously.
See error: a popup appears asking for permission to send messages.
Expected vs Actual Behavior

Expected: SMS should be sent without any permission prompt, as the settings have been changed to allow premium SMS and not ask for permission.
Actual: A popup appears asking for permission to send messages every time multiple SMS are sent simultaneously.

Environment

App Version: 1.15.3
Mode: Private
Operation: Sending SMS
Network Type: WiFi
Smartphone motog51

Device: Motorola G51
OS: Android 11
Additional Context
I have already changed the settings to allow premium SMS and not to ask for permission, but the popup still appears every time I send multiple SMS simultaneously.

**Comment by capcom6** [comment]
Hello, @watata84 

Could you please provide a screenshot of the message you're receiving?

It appears there might be a misunderstanding regarding the request format. According to the documentation, the correct field for specifying phone numbers is `phoneNumbers` as an array, not `phone_number`. You can find more details here: https://capcom6.github.io/android-sms-gateway/#/Messages/post-messages. To clarify, when you mention sending multiple SMS simultaneously, are you referring to including multiple numbers in the `phoneNumbers` array within a single request, or are you sending multiple requests each with a single phone number?

Additionally, have you followed the steps outlined in https://sms.capcom.me/faq/errors/#result_error_limit_exceeded-error including https://www.xda-developers.com/change-sms-limit-android/ to modify SMS sending limits on your device?

**Comment by watata84** [comment]
Thank you for your response.

I have followed the steps outlined in the provided documentation to change the SMS sending limits on my device. Specifically, I modified the SMS limit using the instructions from [XDA Developers](https://www.xda-developers.com/change-sms-limit-android/). However, despite these changes, I am still receiving a notification indicating that an application is attempting to send too many SMS.

It appears that the configuration change did not resolve the issue. I am still seeing a message that says an application is trying to send multiple SMS. To provide more context, I am using a Python script that sends many SMS messages, but each message is sent to a different phone number.

Could you provide further guidance or suggest additional steps I might take to address this?

I greatly appreciate your attention and I highly value the work you do.

Thank you for your assistance.

**Comment by capcom6** [comment]
Thank you for your detailed response and for following the steps to address the issue.

It seems there might be a misunderstanding regarding the request format for sending SMS through our service. Based on your description, it's important to ensure that the request adheres to the expected structure. Could you kindly provide a valid example of the request you are using?

Additionally, could you please provide the following information:

- A screenshot of the notification displayed on your phone regarding the attempt to send too many SMS messages.
- Confirmation on whether you are using multiple phone numbers in the `phoneNumbers` array for your requests.
- The total number of messages you are attempting to send.
- The length of a single message you are sending.
- Details on the specific parameters you have set via ADB to adjust the SMS sending limits.
- Any error messages or statuses displayed on the Messages tab of the app for messages that were not sent following the notification.

This information will greatly aid in diagnosing and potentially resolving the issue at hand.

**Comment by capcom6** [comment]
Hello!

Unfortunately, I didn't receive your answer, so I'll close the issue. However, please feel free to open a new one if you have any further questions.
